on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: WebPageTest Action
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: WebPageTest GitHub Action
        uses: WPO-Foundation/webpagetest-github-action@v1.1.2

        with:
          apiKey: ${{ secrets.WPT_API_KEY }}
          urls: |
            https://adventures.polaris.com/
          label: 'GitHub Action Test'
          budget: 'wpt-budget.json'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
